services:
  newsletter.admin.content:
    class: WebEtDesign\NewsletterBundle\Admin\NewsletterContentAdmin
    arguments:
      - ~
      - WebEtDesign\NewsletterBundle\Entity\Content
      - ~
      - '@security.token_storage'
      - '%wd_newsletter.entity.media%'
      - '@newsletter.newsletter_provider'
      - '%wd_newsletter.locales%'
      - '%wd_newsletter.entity.document%'
      - '%wd_newsletter.entity.actuality%'
    tags:
      - { name: sonata.admin, manager_type: orm, group: NEWSLETTER, label: Content, show_in_dashboard: false }
    public: true

  newsletter.admin.unsub:
    class: WebEtDesign\NewsletterBundle\Admin\NewsletterUnsubAdmin
    arguments:
      - ~
      - WebEtDesign\NewsletterBundle\Entity\Unsubscribe
      - ~
    tags:
      - { name: sonata.admin, manager_type: orm, group: newsletter, label: Désabonnement }
    public: true

  newsletter.admin.newsletter:
    class: WebEtDesign\NewsletterBundle\Admin\NewsletterNewsletterAdmin
    arguments:
      - ~
      - '%wd_newsletter.entity.newsletter%'
      - WebEtDesign\NewsletterBundle\Controller\Admin\NewsletterAdminController
      - '@security.token_storage'
    tags:
      - { name: sonata.admin, manager_type: orm, group: newsletter, label: Newsletter }
    public: true
    calls:
      - [setTemplate, ['show', 'WDNewsletterBundle:admin/newsletter:show.html.twig']]
      - [setFormContractor, ['@cms.sonata.form_contractor.bridge']]

  WebEtDesign\NewsletterBundle\Controller\Admin\NewsletterAdminController:
    autowire: true
    arguments:
      - '@newsletter.email_service'
      - '@doctrine.orm.default_entity_manager'
    tags: ['controller.service_arguments']
