services:
  WebEtDesign\NewsletterBundle\Command\NewsletterSyncContentCommand:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@WebEtDesign\NewsletterBundle\Repository\NewsletterRepository'
      - '@WebEtDesign\NewsletterBundle\Services\NewsletterContentSynchronizer'
    tags:
      - { name: 'console.command', command: 'newsletter:sync-contents' }
