services:
  WebEtDesign\NewsletterBundle\Command\NewsletterSyncContentCommand:
    arguments:
      - ~
      - '@doctrine.orm.default_entity_manager'
      - '@newsletter.newsletter_repository'
      - '@WebEtDesign\NewsletterBundle\Factory\NewsletterFactory'
    tags:
      - { name: 'console.command', command: 'newsletter:sync-contents' }
