services:
  newsletter.admin.newsletter_listener:
    class: WebEtDesign\NewsletterBundle\EventListener\NewsletterAdminListener
    arguments:
      - '@WebEtDesign\NewsletterBundle\Factory\NewsletterFactory'
      - '@doctrine.orm.default_entity_manager'
      - '%wd_newsletter.locales%'
    tags:
      - { name: doctrine.event_listener, event: prePersist }
