services:
  newsletter.newsletter_provider:
    class: WebEtDesign\NewsletterBundle\Services\ModelProvider
    public: true
    arguments: ['%wd_newsletter.models%']

  WebEtDesign\NewsletterBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Admin}'

  WebEtDesign\NewsletterBundle\Controller\UnsubController:
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '%wd_newsletter.routes%'
    tags: ['controller.service_arguments']

  WebEtDesign\NewsletterBundle\Controller\NewsletterContentController:
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\NewsletterBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']

  WebEtDesign\NewsletterBundle\Form\NewsletterModelType:
    arguments:
      - '@newsletter.newsletter_provider'
    tags:
      - { name: form.type }

  WebEtDesign\NewsletterBundle\Form\NewsletterContentCollectionType:
    arguments:
      - '@newsletter.content_collection_transformer'
    tags:
      - { name: form.type }

  newsletter.twig.extension:
    class: WebEtDesign\NewsletterBundle\Twig\NewsletterTwigExtension
    tags:
      - { name: twig.extension }
    public: true
    autowire: true
    arguments:
      - '@newsletter.email_service'

  newsletter.newsletter_repository:
    class: WebEtDesign\NewsletterBundle\Repository\NewsletterRepository
    autowire: true
    public: true

  newsletter.email_service:
    class: WebEtDesign\NewsletterBundle\Services\EmailService
    public: true
    arguments:
      - '@=service(parameter("wd_newsletter.mailer"))'
      - '@templating'
      - '@newsletter.newsletter_provider'
      - '@doctrine.orm.default_entity_manager'
      - '@event_dispatcher'
      - '%wd_newsletter.noreply%'
      - '@router'
      - '%wd_newsletter.locales%'
      - '%kernel.project_dir%'

  newsletter.content_creator_service:
    class: WebEtDesign\NewsletterBundle\Services\NewsletterContentCreatorService
    public: true
    arguments:
      - '%wd_newsletter.locales%'
      - '@doctrine.orm.default_entity_manager'

  newsletter.content_collection_transformer:
    class: WebEtDesign\NewsletterBundle\Form\Transformer\ContentCollectionTransformer
    public: true
    autowire: true