services:

  sonata.admin.request.fetcher:
    class: Sonata\AdminBundle\Request\AdminFetcher
    public: true
    arguments:
      - '@sonata.admin.pool'

  WebEtDesign\NewsletterBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Admin}'

  WebEtDesign\NewsletterBundle\Controller\:
    resource: '../../Controller/*'
    autowire: true
    public: true
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\NewsletterBundle\Controller\UnsubController:
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '%wd_newsletter.routes%'
    tags: ['controller.service_arguments']

  WebEtDesign\NewsletterBundle\Controller\NewsletterContentController:
    public: true
    arguments:
      - '@doctrine.orm.default_entity_manager'
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\NewsletterBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']

  WebEtDesign\NewsletterBundle\Form\NewsletterModelType:
    arguments:
      - '@WebEtDesign\NewsletterBundle\Factory\NewsletterFactory'
    tags:
      - { name: form.type }

  WebEtDesign\NewsletterBundle\Form\AdminNewsletterType:
    arguments:
      - '@WebEtDesign\CmsBundle\Factory\BlockFactory'
      - '%wd_newsletter.locales%'
    tags:
      - { name: form.type }

  WebEtDesign\NewsletterBundle\Form\NewsletterContentType:
    arguments:
      - '@WebEtDesign\CmsBundle\Factory\BlockFactory'
    tags:
      - { name: form.type }

  WebEtDesign\NewsletterBundle\Form\NewsletterContentCollectionType:
    arguments:
#      - '@newsletter.content_collection_transformer'
    tags:
      - { name: form.type }

  newsletter.twig.extension:
    class: WebEtDesign\NewsletterBundle\Twig\NewsletterTwigExtension
    tags:
      - { name: twig.extension }
    public: true
    autowire: true

  newsletter.newsletter_repository:
    class: WebEtDesign\NewsletterBundle\Repository\NewsletterRepository
    autowire: true
    public: true

  WebEtDesign\NewsletterBundle\Services\EmailService:
    public: true
    arguments:
      - '@messenger.bus.default'
      - '@twig'
      - '@WebEtDesign\NewsletterBundle\Factory\NewsletterFactory'
      - '@doctrine.orm.default_entity_manager'
      - '@event_dispatcher'
      - '%wd_newsletter.noreply%'
      - '%wd_newsletter.replyTo%'
      - '@router'
      - '%wd_newsletter.locales%'
      - '%kernel.project_dir%'
      - '%wd_newsletter.enable_log%'
      - '%wd_newsletter.entity.user%'

  newsletter.content_collection_transformer:
    class: WebEtDesign\NewsletterBundle\Form\Transformer\ContentCollectionTransformer
    public: true
    autowire: true

  newsletter.sent_subscriber:
    class: WebEtDesign\NewsletterBundle\Subscriber\NewsletterSentSubscriber
    autowire: true
    public: truc
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '%wd_newsletter.enable_log%'